### ISSUE TITLE
NoSuchFileException in JointGenotyping

### ISSUE THREAD

**Issue by timjeske** [gatk-workflows/gatk4-germline-snps-indels#13]
Dear GATK developers, 

I have a question regarding the ImportGVCFs step of JointGenotyping. 
Independent of the file path (relative or absolute) in the sample name map, I get the following error although the file is existing and readable:

`Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/JointGenotyping/9d5f94a1-46fe-4e79-b671-676b61e10740/call-ImportGVCFs/shard-98/execution/tmp.Zzmonv
[March 9, 2018 8:00:55 AM UTC] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=4116185088
htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/pa.hg38.g.vcf.gz, for input source: file:///storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/pa.hg38.g.vcf.gz
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:254)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:101)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:126)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:110)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.getReaderFromPath(GenomicsDBImport.java:620)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.getHeaderFromPath(GenomicsDBImport.java:355)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.initializeHeaderAndSampleMappings(GenomicsDBImport.java:341)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.onStartup(GenomicsDBImport.java:296)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
Caused by: java.nio.file.NoSuchFileException: /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/pa.hg38.g.vcf.gz
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at htsjdk.samtools.seekablestream.SeekablePathStream.<init>(SeekablePathStream.java:41)
        at htsjdk.tribble.util.ParsingUtils.openInputStream(ParsingUtils.java:110)
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:244)
        ... 13 more
Using GATK wrapper script /gatk/build/install/gatk/bin/gatk
Running:
    /gatk/build/install/gatk/bin/gatk GenomicsDBImport --genomicsdb-workspace-path genomicsdb --batch-size 50 -L chrY:26753603-57227415 --sample-name-map /cromwell-executions/JointGenotyping/9d5f94a1-46fe-4e79-b671-676b61e10740/call-ImportGVCFs/shard-98/inputs/storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/sample_name_map.txt --reader-threads 5 -ip 500
`

I'm using the latest version of cromwell (30.2). Do you have some idea how this can be solved?
There are no hard links of the input g.vcf file in the inputs folder but there is also no error message in the logs that hard linking fails. Could this still be the reason?

**Comment by timjeske** [comment]
I've tried to run JointDiscovery with the example files for NA12878 and the same error occurs. I've also added the fields `"JointDiscovery_GATK4.input_gvcfs_list"` and `"JointDiscovery_GATK4.input_gvcfs_indices_list"` in the inputs.json but that doesn't help either.
Now, I have no idea what else I could try. Maybe the issue is caused because I don't run it on the cloud?

**Comment by bshifaw** [comment]
Hi,
Mind posting the json file being used to execute the wdl along with the command.

**Comment by timjeske** [comment]
Hi, 

attached you can find my inputs.json, the wdl (I've added a docker_user at some points to avoid that docker is running as root), the conf (to limit the number concurrent workflows) and the command to call joint discovery. Do you need any further information?

[joint-discovery-gatk4.hg38.wgs.example.inputs.json.txt](https://github.com/gatk-workflows/gatk4-germline-snps-indels/files/1803164/joint-discovery-gatk4.hg38.wgs.example.inputs.json.txt)
[joint-discovery-gatk4.wdl.txt](https://github.com/gatk-workflows/gatk4-germline-snps-indels/files/1803169/joint-discovery-gatk4.wdl.txt)
[my.conf.txt](https://github.com/gatk-workflows/gatk4-germline-snps-indels/files/1803167/my.conf.txt)
[run_gatk4-joint-discovery-docker_user-cohort_example.sh.txt](https://github.com/gatk-workflows/gatk4-germline-snps-indels/files/1803168/run_gatk4-joint-discovery-docker_user-cohort_example.sh.txt)

**Comment by bshifaw** [comment]
Try the following commands and post here please. 
1. Run command `ls -l /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/`
2. Run `cat /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/rc`
(to confirm a successful attempt)
3. Show the sample name map `cat /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/JointGenotyping/9d5f94a1-46fe-4e79-b671-676b61e10740/call-ImportGVCFs/shard-98/inputs/*`

**Comment by timjeske** [comment]
Ok, here are the results:

1. `-rw-r--r--. 1 tim.jeske OG-IBIS-User         64 Mar  7 00:37 docker_cid`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User 1114733196 Mar  8 14:21 pa.hg38.g.vcf.gz`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User    3449641 Mar  7 00:42 pa.hg38.g.vcf.gz.tbi`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User          2 Mar  7 00:42 rc`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User      18309 Mar  7 00:37 script`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User        948 Mar  7 00:37 script.background`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User        817 Mar  7 00:37 script.submit`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User    1251119 Mar  7 00:42 stderr`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User          0 Mar  7 00:37 stderr.background`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User        189 Mar  7 00:42 stdout`
`-rw-r--r--. 1 tim.jeske OG-IBIS-User          6 Mar  7 00:37 stdout.background`
`drwxrwxrwx. 3 tim.jeske OG-IBIS-User         14 Mar  7 00:42 tmp.wVjQAf`
`
2. 0

3. I'm running `cat /storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/JointGenotyping/9d5f94a1-46fe-4e79-b671-676b61e10740/call-ImportGVCFs/shard-98/inputs/storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/sample_name_map.txt` instead and here is the relevant line:

`pa	/storageNGS/ngs3/projects/other1/KinderKlinik/Exomes/04_GRCh8_GATK4_cohort/GATK4_testrun/cromwell-executions/HaplotypeCallerGvcf_GATK4/3e5a2ae0-5529-4344-b187-9ceac771e1ed/call-MergeGVCFs/execution/pa.hg38.g.vcf.gz
`

**Comment by bshifaw** [comment]
Hey timjeske, 
This wasn't something I was able to quickly solve but you may  be correct about the issue being related to running the wdl locally vs cloud.  You'll have better luck and more help in the gatk forum.  Please post this question along with a link to this issue in [gatk forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team).

**Comment by bshifaw** [comment]
Hi @timjeske 
The repo has been updated to include a gcloud and local version for the joint-discovery wdl

**Comment by timjeske** [comment]
That's great, thank you very much @bshifaw !
