### ISSUE TITLE
hsql causing Java heap size error

### ISSUE THREAD

**Issue by bshifaw** [gatk-workflows/gatk4-germline-snps-indels#6]
I get the following error when running the workflow. 

Command:
java -Dconfig.file=google-adc.conf -Dbackend.providers.JES.config.project=my-project -Dbackend.providers.JES.config.root=gs://my-bucket/gatk4-germline-snps-indels -jar cromwell-29.jar run gatk4-germline-snps-indels/joint-discovery-gatk4.wdl -i gatk4-germline-snps-indels/joint-discovery-gatk4.hg38.wgs.inputs.json

Error:
[2017-10-19 21:19:50,96] [error] Failed to properly flush metadata to database
java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
    at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15(JdbcActionComponent.scala:531)
    at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15$adapted(JdbcActionComponent.scala:529)
    at scala.collection.Iterator.foreach(Iterator.scala:929)
    at scala.collection.Iterator.foreach$(Iterator.scala:929)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
    at scala.collection.IterableLike.foreach(IterableLike.scala:71)
    at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$14(JdbcActionComponent.scala:529)
    at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:372)
    at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:367)
    at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:434)
    at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:502)
    at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:527)
    at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:31)
    at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
    at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
    at scala.collection.Iterator.foreach(Iterator.scala:929)
    at scala.collection.Iterator.foreach$(Iterator.scala:929)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
    at scala.collection.IterableLike.foreach(IterableLike.scala:71)
    at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
    at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)
    at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)
    at scala.collection.Iterator.foreach(Iterator.scala:929)
    at scala.collection.Iterator.foreach$(Iterator.scala:929)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
    at scala.collection.IterableLike.foreach(IterableLike.scala:71)
    at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)
    at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:571)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
    at org.hsqldb.error.Error.error(Unknown Source)
    at org.hsqldb.SessionData.allocateLobForResult(Unknown Source)
    at org.hsqldb.Session.allocateResultLob(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source)
    ... 42 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
Add Comment Collapse

**Comment by vdauwera** [comment]
Looks like your Cromwell is out of memory -- how/what are you running on?

**Comment by bshifaw** [comment]
I ran the workflow on a local VM thats configured with 4G of mem, using the [(cromwell on google cloud)](https://docs.google.com/document/d/1DXbcgs6Kr2sbboNr332YkgD5o_20jfU961c0xp52nQM/edit#) instructions. ftfy suggested adding a java argument to the command to increase memory (-Xmx2048m). But i still got the same error. Also, I ran it on a gcloud instance with 3.5G memory and received the same error. 

Finally,  I followed @ruchim instructions on setting up a local mysql database and configured the google-adc.conf file to use the mysql database. I ran the workflow again on the gcloud instance without the java memory option (-Xmx2048m) and it completed.

**Comment by bshifaw** [comment]
I was told hsql would not be sufficient in handling large input samples like the one i was using, thus setting up mysql would be the solution in this case. 
install mysql:
Found here: https://cloud.google.com/solutions/setup-mysql#how_to_choose_the_right_mysql_deployment_option

create database:
`mysql -u root -p`
`mysql> CREATE DATABASE <database_name>;`

add the following in the google config file, make sure to change <database_name>:
```
database {
 profile = "slick.jdbc.MySQLProfile$"
 db {
      url = "jdbc:mysql://localhost/<database_name>?useSSL=false&rewriteBatchedStatements=true"
       user = "root"
       password = ""
       driver = "com.mysql.jdbc.Driver"
       numThreads = 100
       connectionTimeout = 5000 // NOTE: The default 1000ms is often too short for production mysql use
  }

  insert-batch-size = 2000

   migration {
     read-batch-size = 100000
     write-batch-size = 100000
   }
}
```
